source 'https://github.com/restjohn/CarobTree.git'
source 'https://github.com/CocoaPods/Specs.git'

# Uncomment this line to define a global platform for your project

target 'InteractiveReports' do
  pod 'objective-zip', '0.8.3'
  # override WhirlyGlobe's protobuf dependency, because it did not build with the latest GoogleProtobuf
  pod 'GoogleProtobuf', '2.5.0'
  pod 'WhirlyGlobe', '2.3'
  pod 'iOS-KML-Framework', :git => 'https://github.com/FLCLjp/iOS-KML-Framework.git'
end

